annotations:
  artifacthub.io/changes: |
    - description: Don't overwrite ``.Values.airflowPodAnnotations``
      kind: fixed
      links:
      - name: '#37917'
        url: https://github.com/apache/airflow/pull/37917
    - description: Fix cluster-wide RBAC naming clash when using multiple ``multiNamespace``
        releases with the same name
      kind: fixed
      links:
      - name: '#37197'
        url: https://github.com/apache/airflow/pull/37197
    - description: 'Misc: Default airflow version to 2.8.3'
      kind: changed
      links:
      - name: '#38036'
        url: https://github.com/apache/airflow/pull/38036
  artifacthub.io/links: |
    - name: Documentation
      url: https://airflow.apache.org/docs/helm-chart/1.13.1/
  artifacthub.io/screenshots: |
    - title: DAGs View
      url: https://airflow.apache.org/docs/apache-airflow/2.8.3/_images/dags.png
    - title: Datasets View
      url: https://airflow.apache.org/docs/apache-airflow/2.8.3/_images/datasets.png
    - title: Grid View
      url: https://airflow.apache.org/docs/apache-airflow/2.8.3/_images/grid.png
    - title: Graph View
      url: https://airflow.apache.org/docs/apache-airflow/2.8.3/_images/graph.png
    - title: Calendar View
      url: https://airflow.apache.org/docs/apache-airflow/2.8.3/_images/calendar.png
    - title: Variable View
      url: https://airflow.apache.org/docs/apache-airflow/2.8.3/_images/variable_hidden.png
    - title: Gantt Chart
      url: https://airflow.apache.org/docs/apache-airflow/2.8.3/_images/gantt.png
    - title: Task Duration
      url: https://airflow.apache.org/docs/apache-airflow/2.8.3/_images/duration.png
    - title: Code View
      url: https://airflow.apache.org/docs/apache-airflow/2.8.3/_images/code.png
apiVersion: v2
appVersion: 2.8.3
dependencies:
- condition: postgresql.enabled
  name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 13.2.24
description: The official Helm chart to deploy Apache Airflow, a platform to programmatically
  author, schedule, and monitor workflows
home: https://airflow.apache.org/
icon: https://airflow.apache.org/images/airflow_dark_bg.png
keywords:
- apache
- airflow
- workflow
- scheduler
maintainers:
- email: dev@airflow.apache.org
  name: Apache Airflow PMC
name: airflow
sources:
- https://github.com/apache/airflow
type: application
version: 1.13.1
